### ISSUE TITLE
Airbnb allow double-equals on null

### ISSUE THREAD

**Issue by unindented** [progre/tslint-config-airbnb#13]
Airbnb's guidelines are cool with ` foo == null`, but your config doesn't.

See here: https://github.com/airbnb/javascript/blob/57ff032b0740ba2a46af4bc40cf5638a3e62a365/packages/eslint-config-airbnb-base/rules/best-practices.js#L40

You should probably be using:

```
"triple-equals": [true, "allow-null-check"]
```

**Comment by progre** [comment]
Thx to your pointed out!

As a matter of fact, I recently made this change; b4210920617bcf1366e5cf11ba473a15bfb47fac
The reason is, The style guide can be read like to completely prohibite == and !=,
and recommend to use check to not use null like this ``` if (object) { ... } ```
(15.1, 15.2, and 15.3 in https://github.com/airbnb/javascript#comparison-operators--equality)

I'm going to confirm that with them.
You can use previous version.  ```npm install tslint-config-airbnb@5.1.2```

**Comment by unindented** [comment]
Ah sorry, didn't see that commit!

I'm using their `eslint-config-airbnb` in my JS projects, and I use `== null` everywhere, so I'm pretty sure they are cool with that use case.

**Comment by progre** [comment]
blocked by airbnb/javascript#1473

**Comment by progre** [comment]
It was confirmed that it can be used in a limited case.

**Comment by progre** [comment]
5.2.0 is unpublishd.
